### ISSUE TITLE
Controls & Settings

### ISSUE THREAD

**Issue by m-e-h** [justintadlock/butterbean#13]
- Options for the color-picker http://automattic.github.io/Iris/#options *`palettes`
- value array setting (checkboxes, multi-select, etc.)
- Multi-select -this would be an easy custom control but the sanitizing is where I struggle. ^^^

**Comment by m-e-h** [comment]
- Taxonomy Term select _(saved as a term)_

**Comment by justintadlock** [comment]
I've split this off into multiple tickets to easier track.  So, I'm going to close this ticket since it doesn't have a specific focus.

> value array setting (checkboxes, multi-select, etc.)

There's an existing `ButterBean_Setting_Array`, which I'm thinking of changing to `ButterBean_Setting_Multiple` because it's not really an array so much as it is storing multiple values for a single key.

Or, do you want to save an array as a single meta value?

**Comment by m-e-h** [comment]
#18 is what I was referring to. :ok_hand:
